### ISSUE TITLE
Change ReadME to reflect new package

### ISSUE THREAD

**Issue by mikeejazmines** [tensor-hq/tensorswap-sdk#2]
GM!

Just a documentation change. I was trying to install the package via the read me using this command `yarn add @tensor-hq/tensorswap-sdk-public` when it kept saying 
```
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@tensor-hq%2ftensorswap-sdk-public: Not found"
````
Saw that you changed the name (https://github.com/tensor-hq/tensorswap-sdk/commit/b56bd321b3f135422dd56d3788d6bd8cdeefa6dc) so I adjusted the command to `yarn add @tensor-hq/tensorswap-sdk` and it worked without an issue. Changing this would ensure that new users can install your package 😄

**Comment by richardwu** [comment]
Oops just seeing this now: fixed a while back :)
